mailchimp/authen/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, PasswordField, SubmitField
from wtforms.validators import DataRequired

class AuthenForm(FlaskForm):
  url = StringField('URL', validators=[DataRequired()])
  api_key = PasswordField('API Key', validators=[DataRequired()])
  submit = SubmitField('Auth')

mailchimp/__init__.py
from flask import Flask

app = Flask(__name__)

app.config['SECRET_KEY'] = 'my_key'

from mailchimp.core.views import core_blueprint
from mailchimp.authen.views import authen_blueprint

app.register_blueprint(core_blueprint)
app.register_blueprint(authen_blueprint)

mailchimp/authen/views.py
from flask import Blueprint, render_template, session, redirect, url_for
from mailchimp.authen.forms import AuthenForm

authen_blueprint = Blueprint('authen', __name__)

@authen_blueprint.route('/', methods=['POST', 'GET'])
@authen_blueprint.route('/index', methods=['POST', 'GET'])
def authen():
  form = AuthenForm()

  if form.validate_on_submit():
    session['url'] = form.url.data
    session['api_key'] = form.api_key.data

    return redirect(url_for('core.lists'))
  
  return render_template('authen.html', form=form)

mailchimp/core/views.py
import json
from flask import Blueprint, redirect, render_template, session, jsonify, make_response, request, url_for
from mailchimp.handlers.handle_member import add_list_member, update_list_member, delete_list_member
from mailchimp.handlers.handle_list import get_all_lists, get_list_members_info, member_subscribe, get_list_members_info_countable

core_blueprint = Blueprint('core', __name__)

USERNAME = 'anystring'

# INDEX (list all list belong user)
@core_blueprint.route('/lists')
def lists():
  try:
    username = USERNAME
    url = session['url']
    api_key = session['api_key']

    response = get_all_lists(url, username, api_key)

    status_code = response.status_code

    return render_template('lists.html', response=response.json(), status_code=status_code)
  except:
    return redirect(url_for('authen.authen'))

@core_blueprint.route('/lists/<list_id>')
def members(list_id):
  try:
    url = session['url']
    api_key = session['api_key']
    username = USERNAME
    list_id = list_id

    response = get_list_members_info(url, list_id, username, api_key)

    status_code = response.status_code

    return render_template('members.html', response=response.json(), status_code=status_code, list_id=list_id)
  except:
    return redirect(url_for('authen.authen'))

@core_blueprint.route('/add', methods=['POST'])
def add():
  username = USERNAME
  url = session['url']
  api_key = session['api_key']

  req = request.get_json()
  #print(req)

  list_id = req['list_id']
  email_address = req['email']
  status = req['status']

  respone = add_list_member(url, list_id, email_address, status, username, api_key)

  res = make_response(jsonify(respone.json()))

  return res

@core_blueprint.route('/update', methods=['POST'])
def update():
  username = USERNAME
  url = session['url']
  api_key = session['api_key']

  req = request.get_json()
  #print(req)

  list_id = req['list_id']
  subscriber_hash = req['contactId']

  if req['vip'] == 'true':
    vip = True
  else:
    vip = False
  
  member_info = {
    "email_address": req['email'],
    "status": req['status'],
    "email_type": req['emailType'],
    "language": req['language'],
    "merge_fields": {
                  "FNAME": req['merge_fields']['firstName'],
                  "LNAME": req['merge_fields']['lastName'],
                  "ADDRESS": req['merge_fields']['address'],
                  "PHONE": req['merge_fields']['phone'],
                  "BIRTHDAY": req['merge_fields']['birthday'],
                },
    "vip": vip
  }

  respone = update_list_member(url, list_id, subscriber_hash, member_info, username, api_key)

  res = make_response(jsonify(respone.json()))

  return res

@core_blueprint.route('/subscribe', methods=['POST'])
def subscribe():
  username = USERNAME
  url = session['url']
  api_key = session['api_key']

  req = request.get_json()
  #print(req)

  list_id = req['list_id']

  if req['vip'] == 'true':
    vip = True
  else:
    vip = False

  members = [{
    "email_address": req['email'],
    "status": req['status'],
    "email_type": req['emailType'],
    "language": req['language'],
    "merge_fields": {
                  "FNAME": req['merge_fields']['firstName'],
                  "LNAME": req['merge_fields']['lastName'],
                  "ADDRESS": req['merge_fields']['address'],
                  "PHONE": req['merge_fields']['phone'],
                  "BIRTHDAY": req['merge_fields']['birthday'],
                },
    "vip": vip
  }]

  #print(members)
  respone = member_subscribe(url, list_id, members, username, api_key)

  res = make_response(jsonify(respone.json()))

  return res

@core_blueprint.route('/batch_subscribe', methods=['POST'])
def batch_subscribe():
  username = USERNAME
  url = session['url']
  api_key = session['api_key']

  req = request.get_json()
  #print(req)

  list_id = req['list_id']
  members = req['members']

  respone = member_subscribe(url, list_id, members, username, api_key)

  #print(res)
  res = make_response(jsonify(respone.json()))

  return res

@core_blueprint.route('/archive', methods=['POST'])
def archive():
  username = USERNAME
  url = session['url']
  api_key = session['api_key']

  req = request.get_json()
  print(req)

  list_id = req['list_id']
  subscriber_hash = req['subscriber_hash']

  delete_list_member(url, list_id, subscriber_hash, username, api_key)

  #print(res)
  res = make_response(jsonify({"message": "Archived"}), 204)

  return res

@core_blueprint.route('/lists/<list_id>/view/<int:count>', methods=['POST', 'GET'])
def view(list_id, count):
  try:
    username = USERNAME
    url = session['url']
    api_key = session['api_key']

    print(count)

    response = get_list_members_info_countable(url, list_id, count, username, api_key)

    status_code = response.status_code

    return render_template('members.html', response=response.json(), status_code=status_code, list_id=list_id)
  except:
    return redirect(url_for('authen.authen'))

@core_blueprint.route('/session')
def session_page():
  try:
    username = USERNAME
    url = session['url']
    api_key = session['api_key']

    return render_template('sessionPage.html', username=username, url=url, api_key=api_key)
  except:
    return redirect(url_for('authen.authen'))

@core_blueprint.route('/logout')
def logout():
  session.clear()
  return redirect(url_for('authen.authen'))

mailchimp/templates/_render_field.html
{% macro render_error(field) %}
<ul>
    {% for error in field.errors %}
        <li style="color: red">{{ error }}</li>
    {% endfor %}
</ul>
{% endmacro %}

mailchimp/templates/authen.html
{% from "_render_field.html" import render_field, render_error %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link
      rel="stylesheet"
      href="{{ url_for('static', filename='authen.css') }}"
    />
    <!-- CSS only -->
    <link
      href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css"
      rel="stylesheet"
      integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3"
      crossorigin="anonymous"
    />
    <!-- JavaScript Bundle with Popper -->
    <script
      src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"
      integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p"
      crossorigin="anonymous"
    ></script>
    <title>Mailchimp API v3</title>
  </head>
  <body>
    <div class="auth-wrapper">
      <div class="container-fluid">
        <div class="row">
          <div class="col-12 col-sm-5 col-lg-4 text-center text-lg-end">
            <img
              src="{{ url_for('static', filename='mailchimp-logo.svg') }}"
              alt="logo"
              width="240"
              height="240"
            />
          </div>
          <div class="col-12 col-sm-7 col-lg-6 pt-5">
            <form method="POST">
              {{ form.hidden_tag() }}
              <div class="row">
                <div class="col-2">
                  {{ form.url.label(class="form-label label-custom") }}
                </div>
                <div class="col-10">
                  {{ form.url(class="input-control",
                  placeholder="https://{prefix}.api.mailchimp.com/3.0/") }} {{
                  render_error(form.url) }}
                </div>
              </div>
              <hr />
              <div class="row">
                <div class="col-2">
                  {{ form.api_key.label(class="form-label label-custom") }}
                </div>
                <div class="col-10">
                  {{ form.api_key(class="input-control") }} {{
                  render_error(form.api_key) }}
                </div>
              </div>
              <hr />
              <div class="col-12">
                {{ form.submit(class="btn btn-primary") }}
              </div>
            </form>
          </div>
        </div>
      </div>
    </div>
  </body>
</html>

mailchimp/templates/base.html
{% from "_render_field.html" import render_field, render_error %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link
      rel="stylesheet"
      href="{{ url_for('static', filename='main.css') }}"
    />
    <!-- CSS only -->
    <link
      href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css"
      rel="stylesheet"
      integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3"
      crossorigin="anonymous"
    />
    <!-- JavaScript Bundle with Popper -->
    <script
      src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"
      integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p"
      crossorigin="anonymous"
    ></script>
    <title>Mailchimp API v3</title>
  </head>
  <body>
    <!-- NAVBAR -->
    <nav class="navbar-wrapper">
      <div class="row">
        <div class="col-12">
          <ul id="navList">
            <li class="logo">
              <img
                src="{{ url_for('static', filename='mailchimp-logo.svg') }}"
                alt="logo"
                width="120"
                height="120"
              />
            </li>
            <li class="nav-active">
              <a href="{{ url_for('core.lists') }}">Dashboard</a>
            </li>
            <li>
              <div class="dropdown">
                <span class="dropbtn">Other</span>
                <div class="dropdown-content">
                  <a href="#">Subscriber</a>
                  <a href="#">Archived Member</a>
                  <a href="#">Permanent Delete</a>
                </div>
              </div>
            </li>
            <li><a href="{{ url_for('core.session_page') }}">Session</a></li>
            <li><a href="{{ url_for('core.logout') }}">Logout</a></li>
          </ul>
        </div>
      </div>
    </nav>
    <!-- NAVBAR -->

    {% block table %}
    <!--extend stuff-->
    {% endblock table %}
    <script src="{{ url_for('static', filename='base.js') }}"></script>
  </body>
</html>

mailchimp/templates/lists.html
{% extends 'base.html' %} {%block table %} {% if not session['api_key'] %}
<div class="container-fluid">
  <div class="row">
    <div class="col-12 text-center">
      <p>Fetch Data Error</p>
    </div>
  </div>
</div>
{% else %}
<!-- LIST TABLE -->
<section class="table-wrapper">
  <div class="container-fluid">
    <!--CONTROL AREA-->
    <div class="control-wrapper">
      <div class="row">
        <div class="col-12 text-end">
          <input
            id="searchInput"
            type="text"
            class="btn btn-outline-secondary btn-search"
            placeholder="&#128270;"
          />
          <div class="dropdown">
            <button class="dropbtn btn btn-outline-secondary">View</button>
            <div class="dropdown-content">
              <a href="#">10 records</a>
              <a href="#">100 records</a>
              <a href="#">500 records</a>
              <a href="#">All records</a>
            </div>
          </div>
          <button class="btn btn-primary" id="btnRefresh">&#8635;</button>
        </div>
      </div>
    </div>
    <!--CONTROL AREA-->
    <div class="table-responsive">
      <table class="table-custom">
        <thead>
          <th>List Id</th>
          <th>Name</th>
          <th>Email</th>
          <th>Subscribe</th>
          <th>Unsubscriber</th>
        </thead>
        <tbody>
          {% for list in response.lists %}

          <tr>
            <th>
              <a href="{{url_for('core.members', list_id=list.id)}}"
                >{{ list.id }}</a
              >
            </th>
            <td>{{ list.name }}</td>
            <td>{{ list.campaign_defaults.from_email }}</td>
            <td>{{ list.stats.member_count }}</td>
            <td>{{ list.stats.unsubscribe_count }}</td>
          </tr>

          {% endfor %}
        </tbody>
      </table>
    </div>

    <!--CONTROL AREA-->
    <div class="control-wrapper">
      <div class="row">
        <div class="col-12 text-end">
          <button type="button" class="btn btn-primary">&#43;</button>
          <button type="button" class="btn btn-danger">&#8722;</button>
        </div>
      </div>
    </div>
    <!--CONTROL AREA-->
  </div>
</section>

{% endif %} {% endblock table %}

mailchimp/templates/sessionPage.html
{% extends 'base.html' %} {%block table %}
<div class="container-fluid">
  <div class="row mt-5">
    <div class="col-3"></div>
    <div class="col-6">
      <div class="input-group mb-3">
        <span class="input-group-text" id="sessionURL">URL</span>
        <input
          type="text"
          class="form-control"
          value="{{session['url']}}"
          aria-label="Username"
          aria-describedby="sessionURL"
          readonly
        />
      </div>
      <div class="input-group mb-3">
        <span class="input-group-text" id="sessionUsername">Username</span>
        <input
          type="text"
          class="form-control"
          value="{{username}}"
          aria-label="Username"
          aria-describedby="sessionUsername"
          readonly
        />
      </div>
      <div class="input-group mb-3">
        <span class="input-group-text" id="sessionApiKey">API Key</span>
        <input
          type="text"
          class="form-control"
          value="{{session['api_key']}}"
          aria-label="Username"
          aria-describedby="sessionApiKey"
          readonly
        />
      </div>
    </div>
    <div class="col-3"></div>
    <div class="col-12 text-center">
      <button
        class="btn btn-danger"
        data-bs-toggle="modal"
        data-bs-target="#confirmModal"
      >
        End Session
      </button>
    </div>
  </div>
</div>

<!-- Modal -->
<div
  class="modal fade"
  id="confirmModal"
  tabindex="-1"
  aria-labelledby="confirmModalLabel"
  aria-hidden="true"
>
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="confirmModalLabel">Logout?</h5>
        <button
          type="button"
          class="btn-close"
          data-bs-dismiss="modal"
          aria-label="Close"
        ></button>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">
          Close
        </button>
        <button type="button" class="btn btn-danger">
          <a href="{{ url_for('core.logout') }}" style="color: #fff !important">
            End Session
          </a>
        </button>
      </div>
    </div>
  </div>
</div>

{% endblock table %}